### PR TITLE
Platform and dependency updates

### PR DESCRIPTION
**Pull request by kb2ma**
This project has not seen a significant update in several years. Several elements have become obsolete or deprecated. This PR updates dependencies and allows the code to function again. There are no functional changes. Also refreshed README.

### CODE REVIEW

**Review by dfunckt — COMMENTED** [review]
Looks good to me 👍

**Comment by kb2ma** [comment]
@balena-ci retest

**Comment by kb2ma** [comment]
@balena-ci I self-certify!

**Comment by kb2ma** [comment]
@balena-ci retest

**Pull request merged**
